# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  host: aws-us-east-1-portal.12.dblayer.com
  port: 10924
  database: yuvatron-dev
  username: admin
  password: QATOBTQXZIIEUWKZ
  adapter: postgresql